import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Caramelito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen">
          <video autoPlay loop muted className="absolute top-0 left-0 w-full h-full object-cover">
            <source src="/background_web.mp4" type="video/mp4" />
            Tu navegador no soporta el elemento de video.
          </video>
          <div className="relative z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
